-- Instructions
-- In this puzzle you have to go through all the SQL queries and provide us the output of the requests before executing them (ie. make an assumption).
-- Then, execute them to make sure you were correct.
-- Queries
-- CREATE TABLE FirstTab (
--      id integer, 
--      name VARCHAR(10)
-- )
-- INSERT INTO FirstTab VALUES
-- (5,'Pawan'),
-- (6,'Sharlee'),
-- (7,'Krish'),
-- (NULL,'Avtaar')
-- SELECT * FROM FirstTab
-- CREATE TABLE SecondTab (
--     id integer 
-- )
-- INSERT INTO SecondTab VALUES
-- (5),
-- (NULL)
-- SELECT * FROM SecondTab
-- DATA
-- Table1 – FirstTab
-- ID  Name
-- 5   Pawan
-- 6   Sharlee
-- 7   Krish
-- NULL    Avtaar
-- Table2 – SecondTab
-- ID
-- 5
-- NULL
-- Questions
-- Q1. What will be the OUTPUT of the following statement?
--     SELECT COUNT(*) 
--     FROM FirstTab AS ft WHERE ft.id NOT IN ( SELECT id FROM SecondTab WHERE id IS NULL )
-- Predicted: 3
-- Actual: 0
-- This is because the subquery returns NULL, and using IN or NOT IN with a list
-- that has a NULL will result in UNKNOWN, so the full condition becomes ft.id IS UNKNOWN 
-- which is always false.
-- Q2. What will be the OUTPUT of the following statement?
--     SELECT COUNT(*) 
--     FROM FirstTab AS ft WHERE ft.id NOT IN ( SELECT id FROM SecondTab WHERE id = 5 )
-- Predicted: 3
-- Actual: 2
-- This is also related to Q1: the null from FirstTab is not considered to be in the list that the subquery returns.
-- Q3. What will be the OUTPUT of the following statement?

--     SELECT COUNT(*) 
--     FROM FirstTab AS ft WHERE ft.id NOT IN ( SELECT id FROM SecondTab )
-- Predicted: 0
-- Actual: 0
-- Same as Q1 - any comparison with the list whether it's IN or NOT IN that contains NULL will result in UNKNOWN for
-- all the rows which means they're not counted as the condition becomes false.
-- Q4. What will be the OUTPUT of the following statement?

--     SELECT COUNT(*) 
--     FROM FirstTab AS ft WHERE ft.id NOT IN ( SELECT id FROM SecondTab WHERE id IS NOT NULL )
-- Predicted: 2
-- Actual: 2
-- Same because the NULL id from FirstTab is not considered to be or not be in the list that the subquery returns as
-- this is UNKNOWN, and we don't count 5 since it's in the list that the subquery returns.
select studen.student_id, course.course_ed from student_to_course join course on 
student_to_course.course_id = course.course_id join student on student_to_course.student_id = student.student_id
where course.course_ed = 'Biology' or course.course_ed = 'Mathematics' or course.course_ed = 'Physics' or course.course_ed = 'Chemistry' or course.course_ed = 'Computer Science' or course.course_ed = 'Economics' or course.course_ed = 'History' or course.course_ed = 'Literature' or course.course_ed = 'Philosophy' or course.course_ed = 'Psychology' or course.course_ed = 'Sociology' or course.course_ed = 'Anthropology' or course.course_ed = 'Geography' or course.course_ed = 'Political Science' or course.course_ed = 'Law' or course.course_ed = 'Business' or course.course_ed = 'Accounting' or course.course_ed = 'Marketing' or course.course_ed = 'Management' or course.course_ed = 'Finance' or course.course_ed = 'Statistics' or course.course_ed = 'Engineering' or course.course_ed = 'Architecture' or course.course_ed = 'Medicine' or course.course_ed = 'Nursing' or course.course_ed = 'Dentistry' or course.course_ed = 'Pharmacy' or course.course_ed = 'Veterinary' or course.course_ed = 'Agriculture' or course.course_ed = 'Environmental Science' or course.course_ed = 'Earth Science' or course.course_ed = 'Astronomy' or course.course_ed = 'Chemical Engineering' or course.course_ed = 'Civil Engineering' or course.course_ed = 'Electrical Engineering' or course.course_ed = 'Mechanical Engineering' or course.course_ed = 'Computer Engineering' or course.course_ed = 'Software Engineering' or course.course_ed = 'Industrial Engineering' or course.course_ed = 'Aerospace Engineering' or course.course_ed = 'Biomedical Engineering' or course.course_ed = 'Nuclear Engineering' or course.course_ed = 'Materials Science' or course.course_ed = 'Physics' or course.course_ed = 'Chemistry' or course.course_ed = 'Biology' or course.course_ed = 'Mathematics' or course.course_ed = 'Computer Science' or course.course_ed = 'Economics' or course.course_ed = 'History' or course.course_ed = 'Literature' or course.course_ed = 'Philosophy' or course.course_ed = '
